#Plugin
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Build settings
remote_theme : "TaylanTatli / Moon"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site settings
title: "Devsisters QA blog"
description: > # this means to ignore newlines until "email:"
   DevQA blog

email: seokjun.jin@devsisters.com
#blog logo
logo: "/assets/images/QA-02.png"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/Upper.png"

name: 'DevQA'
author: 'DevQA'
author_image: "/assets/images/1.png"

paginate:	5

url: "https://seokjunjin.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@bbjoony'

#fill in disqus shortname to use disqus
disqus: DevQA-blog


# social icons and sharing options
social:
  - icon:	twitter
    url:	#https://twitter.com/dirkfabisch
    desc: #Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	#https://facebook.com/???
    desc: #Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/seokjunjin
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

markdown: kramdown
